foreground            #e0e7ff
background            #050a14
selection_background  #3b82f6
cursor                #60a5fa

color0  #050a14
color8  #475569
color1  #ef4444
color2  #34d399
color3  #fcd34d
color4  #3b82f6
color5  #c084fc
color6  #22d3ee
color7  #e0e7ff
