# Общие настройки (вне блоков)
splash = false
ipc = true

# Дефолтные обои для всех мониторов (fallback)
wallpaper {
    monitor = 
    path = /home/surfiks/wallpaper/mahiruwal.png
    fit_mode = cover
}

# Явное указание для твоих мониторов
wallpaper {
    monitor = DP-1
    path = /home/surfiks/wallpaper/mahiruwal.png
}

wallpaper {
    monitor = DP-3
    path = /home/surfiks/wallpaper/mahiruwal.png
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/surfiks/wallpaper/mahiruwal.png
}
